### ISSUE TITLE
User Manage Challenge

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#111]
## Challenge lists in profile

Extend the challenge list in the profile to include useful information, and a button to edit the challenge

## Todo

- [x] create kebab menu button on challenge list with actions for a custom lap in it.
- [x] allow user to edit custom lap
- [x] add link to get to share tools
- [x] add link to get to display map
- [x] prevent user creating challenge twice
- [x] change private/publilc class to data attribute
