### ISSUE TITLE
KK - create CTA's e.g. after the user has hit the "Done" button

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#162]
- AMEN to your prayers! ❤️
- Prayer tip:
- Using Prayer.Global before a meal, on a break, or at bedtime can help form a world-changing habit!
- Set a recurring task or calendar event to develop prayer disciplines!
- Use Prayer.Global with family or friends!
- Challenge your church or friends to do a custom lap (link) with you!
- Zúme stuff
  - Learn how God uses ordinary people [link]
  - Discover the essence of being a disciple, making a disciple, and what the church is [link]
  - etc.
- Give
- Click here for more options

## TODO
- [x] after celebration change to CTAs
- [x] change top nav to Home | Map
- [x] make a simple nav footer with give in it
- [x] make share button more clickable
- [x] move CTAs to popup on returning to the map screen

**Comment by squigglybob** [comment]
see [Brainstorm in google doc]( https://docs.google.com/document/d/1tZLw4aOSfQ0LU025U9qRy5NwqCW-hDwmbNWrWRwg1X0/edit)

**Comment by squigglybob** [comment]
Maybe this would be better as a modal after they have gone to the map screen?
